import type { User, Workspace, Project, Task, Team } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "/professional-male-avatar.png",
    role: "admin",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "/professional-female-avatar.png",
    role: "member",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@example.com",
    avatar: "/professional-male-developer-avatar.png",
    role: "member",
  },
]

export const mockWorkspaces: Workspace[] = [
  {
    id: "1",
    _id: "1",
    name: "Acme Corporation",
    description: "Main workspace for Acme Corporation projects",
    avatar: "/blue-corporate-logo.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
    members: [
      {
        id: "1",
        userId: "1",
        workspaceId: "1",
        role: "admin",
        joinedAt: new Date("2024-01-01"),
        user: mockUsers[0],
      },
      {
        id: "2",
        userId: "2",
        workspaceId: "1",
        role: "member",
        joinedAt: new Date("2024-01-02"),
        user: mockUsers[1],
      },
    ],
    projects: [],
  },
  {
    id: "2",
    _id: "2",
    name: "Design Team",
    description: "Creative projects and design work",
    avatar: "/design-creative-logo-purple.jpg",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-20"),
    members: [
      {
        id: "3",
        userId: "2",
        workspaceId: "2",
        role: "admin",
        joinedAt: new Date("2024-01-10"),
        user: mockUsers[1],
      },
    ],
    projects: [],
  },
]

export const mockProjects: Project[] = [
  {
    id: "1",
    _id: "1",
    name: "Website Redesign",
    key: "WR",
    description: "Complete redesign of the company website with modern UI/UX principles",
    avatar: "/website-project-icon.jpg",
    workspaceId: "1",
    leadId: "1",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-20"),
    members: [
      {
        id: "1",
        userId: "1",
        projectId: "1",
        role: "admin",
        joinedAt: new Date("2024-01-05"),
        user: mockUsers[0],
      },
      {
        id: "2",
        userId: "2",
        projectId: "1",
        role: "member",
        joinedAt: new Date("2024-01-06"),
        user: mockUsers[1],
      },
    ],
    boards: [
      {
        id: "1",
        name: "Website Redesign Board",
        type: "kanban",
        projectId: "1",
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-01-20"),
        columns: [
          {
            id: "1",
            name: "To Do",
            boardId: "1",
            position: 0,
            tasks: [],
          },
          {
            id: "2",
            name: "In Progress",
            boardId: "1",
            position: 1,
            tasks: [],
          },
          {
            id: "3",
            name: "Review",
            boardId: "1",
            position: 2,
            tasks: [],
          },
          {
            id: "4",
            name: "Done",
            boardId: "1",
            position: 3,
            tasks: [],
          },
        ],
      },
    ],
  },
  {
    id: "2",
    _id: "2",
    name: "Mobile App Development",
    key: "MAD",
    description: "Native mobile application for iOS and Android platforms",
    avatar: "/generic-mobile-app-icon.png",
    workspaceId: "1",
    leadId: "2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-25"),
    members: [
      {
        id: "3",
        userId: "2",
        projectId: "2",
        role: "admin",
        joinedAt: new Date("2024-01-15"),
        user: mockUsers[1],
      },
      {
        id: "4",
        userId: "3",
        projectId: "2",
        role: "member",
        joinedAt: new Date("2024-01-16"),
        user: mockUsers[2],
      },
    ],
    boards: [],
  },
  {
    id: "3",
    _id: "3",
    name: "API Integration",
    key: "API",
    description: "Backend API development and third-party service integrations",
    avatar: "/api-integration-icon.png",
    workspaceId: "1",
    leadId: "3",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-10"),
    members: [
      {
        id: "5",
        userId: "3",
        projectId: "3",
        role: "admin",
        joinedAt: new Date("2024-02-01"),
        user: mockUsers[2],
      },
    ],
    boards: [],
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    _id: "1",
    title: "Design homepage mockup",
    description: "Create initial mockup for the new homepage design with modern UI/UX principles",
    status: "In Progress",
    priority: "high",
    type: "story",
    assigneeId: "2",
    reporterId: "1",
    projectId: "1",
    boardId: "1",
    columnId: "2",
    position: 0,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
    assignee: mockUsers[1],
    reporter: mockUsers[0],
  },
  {
    id: "2",
    title: "Set up development environment",
    description: "Configure local development environment with all necessary tools and dependencies",
    status: "To Do",
    priority: "medium",
    type: "task",
    assigneeId: "3",
    reporterId: "1",
    projectId: "1",
    boardId: "1",
    columnId: "1",
    position: 0,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-12"),
    assignee: mockUsers[2],
    reporter: mockUsers[0],
  },
  {
    id: "3",
    _id: "3",
    title: "Fix navigation bug",
    description: "Mobile navigation menu not closing properly on iOS devices",
    status: "Review",
    priority: "high",
    type: "bug",
    assigneeId: "2",
    reporterId: "3",
    projectId: "1",
    boardId: "1",
    columnId: "3",
    position: 0,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-18"),
    assignee: mockUsers[1],
    reporter: mockUsers[2],
  },
  {
    id: "4",
    _id: "4",
    title: "Implement user authentication",
    description: "Add login and registration functionality with JWT tokens",
    status: "Done",
    priority: "high",
    type: "story",
    assigneeId: "1",
    reporterId: "1",
    projectId: "1",
    boardId: "1",
    columnId: "4",
    position: 0,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-10"),
    assignee: mockUsers[0],
    reporter: mockUsers[0],
  },
  {
    id: "5",
    _id: "5",
    title: "Create API documentation",
    description: "Document all API endpoints with examples and response formats",
    status: "To Do",
    priority: "low",
    type: "task",
    assigneeId: "3",
    reporterId: "2",
    projectId: "1",
    boardId: "1",
    columnId: "1",
    position: 1,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    assignee: mockUsers[2],
    reporter: mockUsers[1],
  },
]

export const mockTeams: Team[] = [
  {
    id: "1",
    _id: "1",
    name: "Frontend Development",
    description: "Responsible for all frontend development and UI/UX implementation",
    workspaceId: "1",
    leadId: "2",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-20"),
    members: [
      {
        id: "1",
        userId: "2",
        teamId: "1",
        role: "lead",
        joinedAt: new Date("2024-01-05"),
        user: mockUsers[1],
      },
      {
        id: "2",
        userId: "1",
        teamId: "1",
        role: "member",
        joinedAt: new Date("2024-01-06"),
        user: mockUsers[0],
      },
    ],
  },
  {
    id: "2",
    _id: "2",
    name: "Backend Development",
    description: "API development, database management, and server infrastructure",
    workspaceId: "1",
    leadId: "3",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-25"),
    members: [
      {
        id: "3",
        userId: "3",
        teamId: "2",
        role: "lead",
        joinedAt: new Date("2024-01-10"),
        user: mockUsers[2],
      },
      {
        id: "4",
        userId: "1",
        teamId: "2",
        role: "member",
        joinedAt: new Date("2024-01-12"),
        user: mockUsers[0],
      },
    ],
  },
  {
    id: "3",
    _id: "3",
    name: "Design Team",
    description: "UI/UX design, branding, and visual design for all products",
    workspaceId: "2",
    leadId: "2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-01"),
    members: [
      {
        id: "5",
        userId: "2",
        teamId: "3",
        role: "lead",
        joinedAt: new Date("2024-01-15"),
        user: mockUsers[1],
      },
    ],
  },
]

export const mockBoards = [
  {
    id: "1",
    name: "Website Redesign Board",
    type: "kanban" as const,
    projectId: "1",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-20"),
    columns: [
      {
        id: "1",
        name: "To Do",
        boardId: "1",
        position: 0,
        tasks: [],
      },
      {
        id: "2",
        name: "In Progress",
        boardId: "1",
        position: 1,
        tasks: [],
      },
      {
        id: "3",
        name: "Review",
        boardId: "1",
        position: 2,
        tasks: [],
      },
      {
        id: "4",
        name: "Done",
        boardId: "1",
        position: 3,
        tasks: [],
      },
    ],
  },
]
