/**
 * Module-Permission Mapping & RBAC Catalog
 *
 * SOURCE OF TRUTH: This file mirrors the backend enums from
 * backend/CRM_Tech_Be/src/enums/role.enums.js. Keep them in sync.
 *
 * It also exports:
 *  - MODULE_ACTION_CATALOG: which actions belong to which module (for the role builder)
 *  - MODULE_DISPLAY_NAMES / MODULE_GROUPS: UI grouping & labels
 *  - ROLE_DISPLAY_NAMES / ROLE_DESCRIPTIONS: human-readable role meta
 *  - SIDEBAR_*, PAGE_ROUTE_*, DASHBOARD_ACCESS_*: per-feature permission gates
 */

// ────────────────────────────────────────────────────────────────────
// 1. BACKEND MODULE KEYS (mirrors backend MODULES enum)
// ────────────────────────────────────────────────────────────────────
export const MODULES = {
  PLATFORM: "platform",
  ORGANIZATION: "organization",
  FIRM: "firm",
  CLIENT: "client",
  LEAD: "lead",
  INVOICE: "invoice",
  TAX: "tax",
  USER: "user",
  DOCUMENT: "document",
  // NOTE: Backend's MODULES enum has a duplicate REPORTS key (lines 60 & 72 of
  // role.enums.js). Duplicate keys → last value wins in JS → effective backend
  // value is "REPORTS" (uppercase). Mirror that here so role saves validate.
  // After backend item #8 in BACKEND_RBAC_CHANGES.md ships (dedupe + lowercase),
  // change this back to "reports".
  REPORTS: "REPORTS",
  ROLE_PERMISSION: "role_permission",
  PROJECT_MANAGEMENT: "project_management",
  HRM_MANAGEMENT: "hrm_management",
  EMPLOYEE: "EMPLOYEE",
  ONBOARDING: "ONBOARDING",
  ATTENDANCE: "ATTENDANCE",
  SHIFT: "SHIFT",
  LEAVE: "LEAVE",
  HOLIDAY: "HOLIDAY",
  PAYROLL: "PAYROLL",
  POLICY: "POLICY",
  SETTINGS: "SETTINGS",
} as const;

export type ModuleKey = (typeof MODULES)[keyof typeof MODULES];

// ────────────────────────────────────────────────────────────────────
// 2. BACKEND PERMISSION KEYS (mirrors backend PERMISSIONS enum — full set)
// ────────────────────────────────────────────────────────────────────
export const PERMISSIONS = {
  // ─── Platform ───
  MANAGE_PLATFORM_SETTINGS: "MANAGE_PLATFORM_SETTINGS",
  MANAGE_SUBSCRIPTIONS: "MANAGE_SUBSCRIPTIONS",
  MANAGE_SUPPORT_SESSIONS: "MANAGE_SUPPORT_SESSIONS",
  VIEW_PLATFORM_ANALYTICS: "VIEW_PLATFORM_ANALYTICS",

  // ─── Organization ───
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  EDIT_ORGANIZATION: "EDIT_ORGANIZATION",
  DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
  SUSPEND_ORGANIZATION: "SUSPEND_ORGANIZATION",
  EXPORT_ORG_DATA: "EXPORT_ORG_DATA",
  VIEW_ORG_ANALYTICS: "VIEW_ORG_ANALYTICS",
  VIEW_ORG: "VIEW_ORG",
  MANAGE_ORG_SESSIONS: "MANAGE_ORG_SESSIONS",
  ENABLE_SUPPORT_SESSIONS: "ENABLE_SUPPORT_SESSIONS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_AUDIT_LOGS: "MANAGE_AUDIT_LOGS",

  // ─── Users ───
  VIEW_USER: "VIEW_USER",
  VIEW_ALL_USERS: "VIEW_ALL_USERS",
  VIEW_USER_PROFILE: "VIEW_USER_PROFILE",
  VIEW_ORG_USER: "VIEW_ORG_USER",
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  SUSPEND_USER: "SUSPEND_USER",
  UPDATE_ORG_USER: "UPDATE_ORG_USER",
  DELETE_ORG_USER: "DELETE_ORG_USER",
  SEND_INVITATION: "SEND_INVITATION",
  INVITE_GUEST: "INVITE_GUEST",

  // ─── Lead ───
  CREATE_LEAD: "CREATE_LEAD",
  EDIT_LEAD: "EDIT_LEAD",
  DELETE_LEAD: "DELETE_LEAD",
  VIEW_LEAD: "VIEW_LEAD",
  ASSIGN_LEAD: "ASSIGN_LEAD",
  VIEW_DELETED_LEAD: "VIEW_DELETED_LEAD",
  RESTORE_LEAD: "RESTORE_LEAD",

  // ─── Client ───
  CREATE_CLIENT: "CREATE_CLIENT",
  EDIT_CLIENT: "EDIT_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",
  RESTORE_CLIENT: "RESTORE_CLIENT",
  VIEW_CLIENT_LIST: "VIEW_CLIENT_LIST",
  VIEW_DELETED_CLIENT: "VIEW_DELETED_CLIENT",

  // ─── Firm ───
  CREATE_FIRM: "CREATE_FIRM",
  EDIT_FIRM: "EDIT_FIRM",
  DELETE_FIRM: "DELETE_FIRM",
  RESTORE_FIRM: "RESTORE_FIRM",
  VIEW_FIRM: "VIEW_FIRM",
  VIEW_DELETED_FIRM: "VIEW_DELETED_FIRM",

  // ─── Project ───
  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  ASSIGN_PROJECT_LEAD: "ASSIGN_PROJECT_LEAD",
  ADD_PROJECT_MEMBER: "ADD_PROJECT_MEMBER",
  REMOVE_PROJECT_MEMBER: "REMOVE_PROJECT_MEMBER",
  VIEW_PROJECT_MEMBERS: "VIEW_PROJECT_MEMBERS",
  EDIT_PROJECT_MEMBERS: "EDIT_PROJECT_MEMBERS",
  VIEW_ASSIGN_PROJECT_MEMBERS: "VIEW_ASSIGN_PROJECT_MEMBERS",
  MANAGE_PROJECT_PERMISSIONS: "MAMAGE_PROJECT_PERMISSIONS", // backend typo preserved; keep value matching backend
  MANAGE_PROJECT_BUDGET: "MANAGE_PROJECT_BUDGET",
  VIEW_PROJECT: "VIEW_PROJECT",
  VIEW_ALL_PROJECT: "VIEW_ALL_PROJECT",
  VIEW_PROJECT_ANALYTICS: "VIEW_PROJECT_ANALYTICS",

  // ─── Workflow ───
  CREATE_WORKFLOW: "CREATE_WORKFLOW",
  EDIT_WORKFLOW: "EDIT_WORKFLOW",
  DELETE_WORKFLOW: "DELETE_WORKFLOW",
  MANAGE_WORKFLOW_TRANSITIONS: "MANAGE_WORKFLOW_TRANSITIONS",
  VIEW_WORKFLOW: "VIEW_WORKFLOW",

  // ─── Board ───
  CREATE_BOARD: "CREATE_BOARD",
  DELETE_BOARD: "DELETE_BOARD",
  EDIT_BOARD_COLUMN: "EDIT_BOARD_COLUMN",
  MANAGE_BOARD_COLUMNS: "MANAGE_BOARD_COLUMNS",
  DELETE_BOARD_COLUMN: "DELETE_BOARD_COLUMN",
  VIEW_BOARD: "VIEW_BOARD",
  VIEW_ALL_BOARD: "VIEW_ALL_BOARD",

  // ─── Automation ───
  CREATE_AUTOMATION_RULE: "CREATE_AUTOMATION_RULE",
  EDIT_AUTOMATION_RULE: "EDIT_AUTOMATION_RULE",
  DELETE_AUTOMATION_RULE: "DELETE_AUTOMATION_RULE",
  ENABLE_AUTOMATION_RULE: "ENABLE_AUTOMATION_RULE",
  DISABLE_AUTOMATION_RULE: "DISABLE_AUTOMATION_RULE",
  VIEW_AUTOMATION_RULE: "VIEW_AUTOMATION_RULE",
  MANAGE_AUTOMATION_TRIGGERS: "MANAGE_AUTOMATION_TRIGGERS",
  MANAGE_AUTOMATION_ACTIONS: "MANAGE_AUTOMATION_ACTIONS",
  MANAGE_AUTOMATION_CONDITIONS: "MANAGE_AUTOMATION_CONDITIONS",
  RUN_AUTOMATION_MANUALLY: "RUN_AUTOMATION_MANUALLY",

  // ─── Task ───
  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  VIEW_TASK: "VIEW_TASK",
  VIEW_ALL_TASKS: "VIEW_ALL_TASKS",
  MOVE_TASKS_BETWEEN_COLUMNS: "MOVE_TASKS_BETWEEN_COLUMNS",
  COMMENT_ON_TASK: "COMMENT_ON_TASK",

  // ─── Team ───
  CREATE_TEAM: "CREATE_TEAM",
  VIEW_TEAM: "VIEW_TEAM",
  EDIT_TEAM: "EDIT_TEAM",
  DELETE_TEAM: "DELETE_TEAM",
  VIEW_ASSIGN_TEAM_MEMBERS: "VIEW_ASSIGN_TEAM_MEMBERS",
  ADD_TEAM_MEMBER: "ADD_TEAM_MEMBER",
  REMOVE_TEAM_MEMBER: "REMOVE_TEAM_MEMBER",
  VIEW_TEAM_MEMBERS: "VIEW_TEAM_MEMBERS",
  ASSIGN_TEAM_ROLE: "ASSIGN_TEAM_ROLE",
  MANAGE_TEAM_SETTINGS: "MANAGE_TEAM_SETTINGS",
  MANAGE_TEAM_PERMISSIONS: "MANAGE_TEAM_PERMISSIONS",
  EDIT_TEAM_MEMBERS: "EDIT_TEAM_MEMBERS",

  // ─── Role & Permissions ───
  CREATE_ROLE: "CREATE_ROLE",
  EDIT_ROLE: "EDIT_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  VIEW_ROLE: "VIEW_ROLE",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  AUDIT_PERMISSIONS: "AUDIT_PERMISSIONS",
  CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",

  // ─── Document ───
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  DOWNLOAD_DOCUMENT: "DOWNLOAD_DOCUMENT",
  SHARE_DOCUMENT: "SHARE_DOCUMENT",
  MANAGE_DOCUMENT_VERSIONS: "MANAGE_DOCUMENT_VERSIONS",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",

  // ─── Reporting ───
  GENERATE_REPORT: "GENERATE_REPORT",
  EXPORT_DATA: "EXPORT_DATA",
  SCHEDULE_REPORTS: "SCHEDULE_REPORTS",
  SHARE_REPORTS: "SHARE_REPORTS",

  // ─── HRM ───
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  SUSPEND_EMPLOYEE: "SUSPEND_EMPLOYEE",
  VIEW_EMPLOYEE_PROFILE: "VIEW_EMPLOYEE_PROFILE",
  VIEW_ALL_EMPLOYEES: "VIEW_ALL_EMPLOYEES",
  UPDATE_EMPLOYEE_PROFILE: "UPDATE_EMPLOYEE_PROFILE",
  MANAGE_EMPLOYE_LEAVE: "MANAGE_EMPLOYE_LEAVE", // backend typo preserved (missing E)
  MANAGE_EMPLOYEE_PERMISSIONS: "MANAGE_EMPLOYEE_PERMISSIONS",
  MANAGE_PAYROLL: "MANAGE_PAYROLL",
  VIEW_PAYSLIPS: "VIEW_PAYSLIPS",
  APPROVE_TIMESHEETS: "APPROVE_TIMESHEETS",
  MANAGE_ATTENDANCE: "MANAGE_ATTENDANCE",
  CREATE_JOB_POSTING: "CREATE_JOB_POSTING",
  EDIT_JOB_POSTING: "EDIT_JOB_POSTING",
  DELETE_JOB_POSTING: "DELETE_JOB_POSTING",
  REVIEW_APPLICATIONS: "REVIEW_APPLICATIONS",
  HIRE_CANDIDATE: "HIRE_CANDIDATE",

  // ─── Generic ───
  VIEW_ONLY: "VIEW_ONLY",
  VIEW_LIMITED_ACCESS: "VIEW_LIMITED_ACCESS",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// ────────────────────────────────────────────────────────────────────
// 3. BACKEND ROLES (mirrors backend ROLES enum — all 30)
// ────────────────────────────────────────────────────────────────────
export const ROLES = {
  // Platform-level
  SUPER_ADMIN: "SuperAdmin",
  PLATFORM_ADMIN: "PlatformAdmin",
  PLATFORM_SUPPORT: "PlatformSupport",
  PLATFORM_BILLING: "PlatformBilling",
  PLATFORM_DEVOPS: "PlatformDevOps",
  PLATFORM_ANALYST: "PlatformAnalyst",
  PLATFORM_CUSTOM: "PlatformCustom",

  // Organization-level
  ORG_OWNER: "OrgOwner",
  ORG_ADMIN: "OrgAdmin",
  FINANCE_MANAGER: "FinanceManager",
  SALES_MANAGER: "SalesManager",
  SUPPORT_AGENT: "SupportAgent",
  ORG_ANALYST: "OrgAnalyst",
  CLIENT_CONTACT: "ClientContact",
  ORG_CUSTOM: "OrgCustom",

  // Workspace-level
  WORKSPACE_ADMIN: "WorkspaceAdmin",
  WORKSPACE_MEMBER: "WorkspaceMember",
  WORKSPACE_VIEWER: "WorkspaceViewer",
  WORKSPACE_CUSTOM: "WorkspaceCustom",

  // Team-level
  TEAM_LEAD: "TeamLead",
  TEAM_MEMBER: "TeamMember",
  TEAM_VIEWER: "TeamViewer",
  TEAM_CUSTOM: "TeamCustom",

  // Project-level
  PROJECT_ADMIN: "ProjectAdmin",
  PROJECT_MEMBER: "ProjectMember",
  PROJECT_VIEWER: "ProjectViewer",
  PROJECT_CUSTOM: "ProjectCustom",

  // HRM-level
  HR_ADMIN: "HRAdmin",
  HR_MANAGER: "HRManager",
  EMPLOYEE: "Employee",
  HR_CUSTOM: "HRCustom",
} as const;

export type RoleSlug = (typeof ROLES)[keyof typeof ROLES];

// ────────────────────────────────────────────────────────────────────
// 4. ROLE SCOPES (mirrors backend ROLE_SCOPE)
// ────────────────────────────────────────────────────────────────────
export const ROLE_SCOPE = {
  PLATFORM: "sc-plat",
  ORGANIZATION: "sc-org",
  WORKSPACE: "sc-wrk",
  PROJECT: "sc-prj",
  TEAM: "sc-tm",
  HRM: "sc-hrm",
  GUEST: "sc-guest",
} as const;

export type ScopeCode = (typeof ROLE_SCOPE)[keyof typeof ROLE_SCOPE];

export const ROLE_SCOPES_MAP: Record<RoleSlug, ScopeCode> = {
  [ROLES.SUPER_ADMIN]: ROLE_SCOPE.PLATFORM,
  [ROLES.PLATFORM_ADMIN]: ROLE_SCOPE.PLATFORM,
  [ROLES.PLATFORM_SUPPORT]: ROLE_SCOPE.PLATFORM,
  [ROLES.PLATFORM_BILLING]: ROLE_SCOPE.PLATFORM,
  [ROLES.PLATFORM_DEVOPS]: ROLE_SCOPE.PLATFORM,
  [ROLES.PLATFORM_ANALYST]: ROLE_SCOPE.PLATFORM,
  [ROLES.PLATFORM_CUSTOM]: ROLE_SCOPE.PLATFORM,
  [ROLES.ORG_OWNER]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.ORG_ADMIN]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.FINANCE_MANAGER]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.SALES_MANAGER]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.SUPPORT_AGENT]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.ORG_ANALYST]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.CLIENT_CONTACT]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.ORG_CUSTOM]: ROLE_SCOPE.ORGANIZATION,
  [ROLES.WORKSPACE_ADMIN]: ROLE_SCOPE.WORKSPACE,
  [ROLES.WORKSPACE_MEMBER]: ROLE_SCOPE.WORKSPACE,
  [ROLES.WORKSPACE_VIEWER]: ROLE_SCOPE.WORKSPACE,
  [ROLES.WORKSPACE_CUSTOM]: ROLE_SCOPE.WORKSPACE,
  [ROLES.TEAM_LEAD]: ROLE_SCOPE.TEAM,
  [ROLES.TEAM_MEMBER]: ROLE_SCOPE.TEAM,
  [ROLES.TEAM_VIEWER]: ROLE_SCOPE.TEAM,
  [ROLES.TEAM_CUSTOM]: ROLE_SCOPE.TEAM,
  [ROLES.PROJECT_ADMIN]: ROLE_SCOPE.PROJECT,
  [ROLES.PROJECT_MEMBER]: ROLE_SCOPE.PROJECT,
  [ROLES.PROJECT_VIEWER]: ROLE_SCOPE.PROJECT,
  [ROLES.PROJECT_CUSTOM]: ROLE_SCOPE.PROJECT,
  [ROLES.HR_ADMIN]: ROLE_SCOPE.HRM,
  [ROLES.HR_MANAGER]: ROLE_SCOPE.HRM,
  [ROLES.EMPLOYEE]: ROLE_SCOPE.HRM,
  [ROLES.HR_CUSTOM]: ROLE_SCOPE.HRM,
};

// ────────────────────────────────────────────────────────────────────
// 5. MODULE-ACTION CATALOG (which actions belong to which module)
//    This is what the role builder uses to render checkboxes.
//    Drives the FULL backend permission set per module.
// ────────────────────────────────────────────────────────────────────
export const MODULE_ACTION_CATALOG: Record<string, string[]> = {
  [MODULES.PLATFORM]: [
    PERMISSIONS.MANAGE_PLATFORM_SETTINGS,
    PERMISSIONS.MANAGE_SUBSCRIPTIONS,
    PERMISSIONS.MANAGE_SUPPORT_SESSIONS,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS,
  ],
  [MODULES.ORGANIZATION]: [
    PERMISSIONS.CREATE_ORGANIZATION,
    PERMISSIONS.EDIT_ORGANIZATION,
    PERMISSIONS.DELETE_ORGANIZATION,
    PERMISSIONS.SUSPEND_ORGANIZATION,
    PERMISSIONS.EXPORT_ORG_DATA,
    PERMISSIONS.VIEW_ORG_ANALYTICS,
    PERMISSIONS.VIEW_ORG,
    PERMISSIONS.MANAGE_ORG_SESSIONS,
    PERMISSIONS.ENABLE_SUPPORT_SESSIONS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_AUDIT_LOGS,
  ],
  [MODULES.USER]: [
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.VIEW_ALL_USERS,
    PERMISSIONS.VIEW_USER_PROFILE,
    PERMISSIONS.VIEW_ORG_USER,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_ORG_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.DELETE_ORG_USER,
    PERMISSIONS.SUSPEND_USER,
    PERMISSIONS.SEND_INVITATION,
    PERMISSIONS.INVITE_GUEST,
  ],
  [MODULES.FIRM]: [
    PERMISSIONS.CREATE_FIRM,
    PERMISSIONS.EDIT_FIRM,
    PERMISSIONS.DELETE_FIRM,
    PERMISSIONS.RESTORE_FIRM,
    PERMISSIONS.VIEW_FIRM,
    PERMISSIONS.VIEW_DELETED_FIRM,
  ],
  [MODULES.CLIENT]: [
    PERMISSIONS.CREATE_CLIENT,
    PERMISSIONS.EDIT_CLIENT,
    PERMISSIONS.DELETE_CLIENT,
    PERMISSIONS.RESTORE_CLIENT,
    PERMISSIONS.VIEW_CLIENT_LIST,
    PERMISSIONS.VIEW_DELETED_CLIENT,
  ],
  [MODULES.LEAD]: [
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.DELETE_LEAD,
    PERMISSIONS.VIEW_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.RESTORE_LEAD,
    PERMISSIONS.VIEW_DELETED_LEAD,
  ],
  [MODULES.INVOICE]: [
    // Backend currently has no INVOICE-specific permissions; reuse generic reporting perms.
    PERMISSIONS.GENERATE_REPORT,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [MODULES.TAX]: [
    // Backend currently has no TAX-specific permissions; reuse generic reporting perms.
    PERMISSIONS.GENERATE_REPORT,
    PERMISSIONS.EXPORT_DATA,
  ],
  [MODULES.DOCUMENT]: [
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.DOWNLOAD_DOCUMENT,
    PERMISSIONS.SHARE_DOCUMENT,
    PERMISSIONS.MANAGE_DOCUMENT_VERSIONS,
    PERMISSIONS.DELETE_DOCUMENT,
  ],
  [MODULES.REPORTS]: [
    PERMISSIONS.GENERATE_REPORT,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.SCHEDULE_REPORTS,
    PERMISSIONS.SHARE_REPORTS,
  ],
  [MODULES.ROLE_PERMISSION]: [
    PERMISSIONS.CREATE_ROLE,
    PERMISSIONS.EDIT_ROLE,
    PERMISSIONS.DELETE_ROLE,
    PERMISSIONS.VIEW_ROLE,
    PERMISSIONS.MANAGE_PERMISSIONS,
    PERMISSIONS.AUDIT_PERMISSIONS,
    PERMISSIONS.CHANGE_MEMBER_ROLE,
  ],
  [MODULES.PROJECT_MANAGEMENT]: [
    // Project core
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.EDIT_PROJECT,
    PERMISSIONS.DELETE_PROJECT,
    PERMISSIONS.VIEW_PROJECT,
    PERMISSIONS.VIEW_ALL_PROJECT,
    PERMISSIONS.VIEW_PROJECT_ANALYTICS,
    PERMISSIONS.MANAGE_PROJECT_BUDGET,
    PERMISSIONS.ASSIGN_PROJECT_LEAD,
    // Project members
    PERMISSIONS.ADD_PROJECT_MEMBER,
    PERMISSIONS.REMOVE_PROJECT_MEMBER,
    PERMISSIONS.VIEW_PROJECT_MEMBERS,
    PERMISSIONS.EDIT_PROJECT_MEMBERS,
    PERMISSIONS.VIEW_ASSIGN_PROJECT_MEMBERS,
    PERMISSIONS.MANAGE_PROJECT_PERMISSIONS,
    // Workflow
    PERMISSIONS.CREATE_WORKFLOW,
    PERMISSIONS.EDIT_WORKFLOW,
    PERMISSIONS.DELETE_WORKFLOW,
    PERMISSIONS.MANAGE_WORKFLOW_TRANSITIONS,
    PERMISSIONS.VIEW_WORKFLOW,
    // Board
    PERMISSIONS.CREATE_BOARD,
    PERMISSIONS.DELETE_BOARD,
    PERMISSIONS.VIEW_BOARD,
    PERMISSIONS.VIEW_ALL_BOARD,
    PERMISSIONS.EDIT_BOARD_COLUMN,
    PERMISSIONS.MANAGE_BOARD_COLUMNS,
    PERMISSIONS.DELETE_BOARD_COLUMN,
    // Automation
    PERMISSIONS.CREATE_AUTOMATION_RULE,
    PERMISSIONS.EDIT_AUTOMATION_RULE,
    PERMISSIONS.DELETE_AUTOMATION_RULE,
    PERMISSIONS.ENABLE_AUTOMATION_RULE,
    PERMISSIONS.DISABLE_AUTOMATION_RULE,
    PERMISSIONS.VIEW_AUTOMATION_RULE,
    PERMISSIONS.MANAGE_AUTOMATION_TRIGGERS,
    PERMISSIONS.MANAGE_AUTOMATION_ACTIONS,
    PERMISSIONS.MANAGE_AUTOMATION_CONDITIONS,
    PERMISSIONS.RUN_AUTOMATION_MANUALLY,
    // Task
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.VIEW_TASK,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.MOVE_TASKS_BETWEEN_COLUMNS,
    PERMISSIONS.COMMENT_ON_TASK,
    // Team
    PERMISSIONS.CREATE_TEAM,
    PERMISSIONS.VIEW_TEAM,
    PERMISSIONS.EDIT_TEAM,
    PERMISSIONS.DELETE_TEAM,
    PERMISSIONS.ADD_TEAM_MEMBER,
    PERMISSIONS.REMOVE_TEAM_MEMBER,
    PERMISSIONS.VIEW_TEAM_MEMBERS,
    PERMISSIONS.EDIT_TEAM_MEMBERS,
    PERMISSIONS.VIEW_ASSIGN_TEAM_MEMBERS,
    PERMISSIONS.ASSIGN_TEAM_ROLE,
    PERMISSIONS.MANAGE_TEAM_SETTINGS,
    PERMISSIONS.MANAGE_TEAM_PERMISSIONS,
  ],
  [MODULES.HRM_MANAGEMENT]: [
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.SUSPEND_EMPLOYEE,
    PERMISSIONS.VIEW_EMPLOYEE_PROFILE,
    PERMISSIONS.VIEW_ALL_EMPLOYEES,
    PERMISSIONS.UPDATE_EMPLOYEE_PROFILE,
    PERMISSIONS.MANAGE_EMPLOYE_LEAVE,
    PERMISSIONS.MANAGE_EMPLOYEE_PERMISSIONS,
    PERMISSIONS.CREATE_JOB_POSTING,
    PERMISSIONS.EDIT_JOB_POSTING,
    PERMISSIONS.DELETE_JOB_POSTING,
    PERMISSIONS.REVIEW_APPLICATIONS,
    PERMISSIONS.HIRE_CANDIDATE,
    PERMISSIONS.APPROVE_TIMESHEETS,
  ],
  [MODULES.EMPLOYEE]: [
    PERMISSIONS.VIEW_EMPLOYEE_PROFILE,
    PERMISSIONS.VIEW_ALL_EMPLOYEES,
    PERMISSIONS.UPDATE_EMPLOYEE_PROFILE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.SUSPEND_EMPLOYEE,
  ],
  [MODULES.ONBOARDING]: [
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.VIEW_EMPLOYEE_PROFILE,
  ],
  [MODULES.ATTENDANCE]: [
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.APPROVE_TIMESHEETS,
  ],
  [MODULES.SHIFT]: [PERMISSIONS.MANAGE_ATTENDANCE],
  [MODULES.LEAVE]: [PERMISSIONS.MANAGE_EMPLOYE_LEAVE],
  [MODULES.HOLIDAY]: [PERMISSIONS.MANAGE_ATTENDANCE],
  [MODULES.PAYROLL]: [
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.VIEW_PAYSLIPS,
  ],
  [MODULES.POLICY]: [
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.MANAGE_EMPLOYE_LEAVE,
  ],
  [MODULES.SETTINGS]: [
    PERMISSIONS.EDIT_ORGANIZATION,
    PERMISSIONS.MANAGE_PLATFORM_SETTINGS,
  ],
};

// ────────────────────────────────────────────────────────────────────
// 6. DISPLAY METADATA
// ────────────────────────────────────────────────────────────────────
export const MODULE_DISPLAY_NAMES: Record<string, string> = {
  [MODULES.PLATFORM]: "Platform",
  [MODULES.ORGANIZATION]: "Organization",
  [MODULES.FIRM]: "Firms",
  [MODULES.CLIENT]: "Clients",
  [MODULES.LEAD]: "Leads",
  [MODULES.INVOICE]: "Billing & Invoices",
  [MODULES.TAX]: "Tax",
  [MODULES.USER]: "Users",
  [MODULES.DOCUMENT]: "Documents",
  [MODULES.REPORTS]: "Reports",
  [MODULES.ROLE_PERMISSION]: "Roles & Permissions",
  [MODULES.PROJECT_MANAGEMENT]: "Project Management",
  [MODULES.HRM_MANAGEMENT]: "HRM",
  [MODULES.EMPLOYEE]: "Employees",
  [MODULES.ONBOARDING]: "Onboarding",
  [MODULES.ATTENDANCE]: "Attendance",
  [MODULES.SHIFT]: "Shifts",
  [MODULES.LEAVE]: "Leave",
  [MODULES.HOLIDAY]: "Holidays",
  [MODULES.PAYROLL]: "Payroll",
  [MODULES.POLICY]: "Policies",
  [MODULES.SETTINGS]: "Settings",
};

export const MODULE_GROUPS: Record<string, string> = {
  [MODULES.PLATFORM]: "Identity & Access",
  [MODULES.ORGANIZATION]: "Identity & Access",
  [MODULES.USER]: "Identity & Access",
  [MODULES.ROLE_PERMISSION]: "Identity & Access",
  [MODULES.FIRM]: "Identity & Access",

  [MODULES.LEAD]: "CRM",
  [MODULES.CLIENT]: "CRM",

  [MODULES.INVOICE]: "Finance",
  [MODULES.TAX]: "Finance",

  [MODULES.DOCUMENT]: "Documents & Reports",
  [MODULES.REPORTS]: "Documents & Reports",

  [MODULES.PROJECT_MANAGEMENT]: "Project Management",

  [MODULES.HRM_MANAGEMENT]: "Human Resources",
  [MODULES.EMPLOYEE]: "Human Resources",
  [MODULES.ONBOARDING]: "Human Resources",
  [MODULES.ATTENDANCE]: "Human Resources",
  [MODULES.SHIFT]: "Human Resources",
  [MODULES.LEAVE]: "Human Resources",
  [MODULES.HOLIDAY]: "Human Resources",
  [MODULES.PAYROLL]: "Human Resources",
  [MODULES.POLICY]: "Human Resources",

  [MODULES.SETTINGS]: "System",
};

export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  [ROLES.SUPER_ADMIN]: "Super Admin",
  [ROLES.PLATFORM_ADMIN]: "Platform Admin",
  [ROLES.PLATFORM_SUPPORT]: "Platform Support",
  [ROLES.PLATFORM_BILLING]: "Platform Billing",
  [ROLES.PLATFORM_DEVOPS]: "Platform DevOps",
  [ROLES.PLATFORM_ANALYST]: "Platform Analyst",
  [ROLES.PLATFORM_CUSTOM]: "Platform Custom",
  [ROLES.ORG_OWNER]: "Organization Owner",
  [ROLES.ORG_ADMIN]: "Organization Admin",
  [ROLES.FINANCE_MANAGER]: "Finance Manager",
  [ROLES.SALES_MANAGER]: "Sales Manager",
  [ROLES.SUPPORT_AGENT]: "Support Agent",
  [ROLES.ORG_ANALYST]: "Organization Analyst",
  [ROLES.CLIENT_CONTACT]: "Client Contact",
  [ROLES.ORG_CUSTOM]: "Organization Custom",
  [ROLES.WORKSPACE_ADMIN]: "Workspace Admin",
  [ROLES.WORKSPACE_MEMBER]: "Workspace Member",
  [ROLES.WORKSPACE_VIEWER]: "Workspace Viewer",
  [ROLES.WORKSPACE_CUSTOM]: "Workspace Custom",
  [ROLES.TEAM_LEAD]: "Team Lead",
  [ROLES.TEAM_MEMBER]: "Team Member",
  [ROLES.TEAM_VIEWER]: "Team Viewer",
  [ROLES.TEAM_CUSTOM]: "Team Custom",
  [ROLES.PROJECT_ADMIN]: "Project Admin",
  [ROLES.PROJECT_MEMBER]: "Project Member",
  [ROLES.PROJECT_VIEWER]: "Project Viewer",
  [ROLES.PROJECT_CUSTOM]: "Project Custom",
  [ROLES.HR_ADMIN]: "HR Admin",
  [ROLES.HR_MANAGER]: "HR Manager",
  [ROLES.EMPLOYEE]: "Employee",
  [ROLES.HR_CUSTOM]: "HR Custom",
};

export const SCOPE_DISPLAY_NAMES: Record<string, string> = {
  [ROLE_SCOPE.PLATFORM]: "Platform",
  [ROLE_SCOPE.ORGANIZATION]: "Organization",
  [ROLE_SCOPE.WORKSPACE]: "Workspace",
  [ROLE_SCOPE.PROJECT]: "Project",
  [ROLE_SCOPE.TEAM]: "Team",
  [ROLE_SCOPE.HRM]: "HRM",
  [ROLE_SCOPE.GUEST]: "Guest",
};

// ────────────────────────────────────────────────────────────────────
// 7. HELPER UTILITIES
// ────────────────────────────────────────────────────────────────────

/**
 * Returns the slug to use for a custom role at a given scope.
 * Backend RolePermission.role enum requires one of the *_CUSTOM values for custom roles.
 */
export function getCustomRoleSlugForScope(scope: ScopeCode): RoleSlug {
  switch (scope) {
    case ROLE_SCOPE.PLATFORM:
      return ROLES.PLATFORM_CUSTOM;
    case ROLE_SCOPE.WORKSPACE:
      return ROLES.WORKSPACE_CUSTOM;
    case ROLE_SCOPE.PROJECT:
      return ROLES.PROJECT_CUSTOM;
    case ROLE_SCOPE.TEAM:
      return ROLES.TEAM_CUSTOM;
    case ROLE_SCOPE.HRM:
      return ROLES.HR_CUSTOM;
    case ROLE_SCOPE.ORGANIZATION:
    case ROLE_SCOPE.GUEST:
    default:
      return ROLES.ORG_CUSTOM;
  }
}

/** Module ids ordered by group for stable rendering */
export const ALL_MODULE_IDS: string[] = Object.values(MODULES);

/** All known permission ids (for validation) */
export const ALL_PERMISSION_IDS: string[] = Object.values(PERMISSIONS);

/** Quick lookup whether a role slug is a system-managed (non-custom) role */
export function isSystemRoleSlug(slug: string): boolean {
  const customs: string[] = [
    ROLES.PLATFORM_CUSTOM,
    ROLES.ORG_CUSTOM,
    ROLES.WORKSPACE_CUSTOM,
    ROLES.PROJECT_CUSTOM,
    ROLES.TEAM_CUSTOM,
    ROLES.HR_CUSTOM,
  ];
  return !customs.includes(slug);
}

// ─── Permission Requirement Type ───────────────────────────────────
export interface PermissionRequirement {
  module: string;
  actions: string[]; // user needs at least ONE of these actions
}

// ─── Sidebar Group Permission Map ──────────────────────────────────
// Maps sidebar group titles → required permissions
// If a user has ANY of the listed module+action combos, they can see the group
export const SIDEBAR_GROUP_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  // Everyone sees Dashboard
  DASHBOARD: [],

  // Everyone sees Calendar
  CALENDAR: [],

  // CRM System - needs lead OR client permissions
  "CRM SYSTEM": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD, PERMISSIONS.CREATE_LEAD] },
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST, PERMISSIONS.CREATE_CLIENT] },
  ],

  // Sales & Commerce - needs lead/client/invoice permissions
  "SALES & COMMERCE": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] },
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
    { module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] },
  ],

  // Support Desk - needs client or org viewing
  "SUPPORT DESK": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_ORG] },
  ],

  // Project Management - needs project permissions
  "PROJECT MANAGEMENT": [
    { module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_PROJECT, PERMISSIONS.VIEW_ALL_PROJECT, PERMISSIONS.CREATE_PROJECT] },
  ],

  // HRM / Workforce - needs HRM permissions
  "HRM / WORKFORCE": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE, PERMISSIONS.CREATE_EMPLOYEE] },
    { module: MODULES.EMPLOYEE, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE] },
    { module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] },
    { module: MODULES.LEAVE, actions: [PERMISSIONS.MANAGE_EMPLOYE_LEAVE] },
    { module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL, PERMISSIONS.VIEW_PAYSLIPS] },
  ],

  // Finance - needs invoice/org permissions
  FINANCE: [
    { module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] },
    { module: MODULES.TAX, actions: [PERMISSIONS.GENERATE_REPORT] },
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_ORG_ANALYTICS] },
  ],

  // Analytics - needs reporting permissions
  ANALYTICS: [
    { module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT, PERMISSIONS.EXPORT_DATA] },
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_ORG_ANALYTICS] },
  ],

  // Administration - needs org admin or role permissions
  ADMINISTRATION: [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION, PERMISSIONS.VIEW_ORG] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.VIEW_ROLE, PERMISSIONS.CREATE_ROLE, PERMISSIONS.MANAGE_PERMISSIONS] },
    { module: MODULES.USER, actions: [PERMISSIONS.VIEW_ALL_USERS, PERMISSIONS.CREATE_USER] },
  ],

  // ─── Admin Sidebar Groups ───────────────────────────────────────
  ORGANIZATION: [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_ORG, PERMISSIONS.EDIT_ORGANIZATION] },
  ],

  "IDENTITY & ACCESS": [
    { module: MODULES.USER, actions: [PERMISSIONS.VIEW_ALL_USERS, PERMISSIONS.CREATE_USER] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.VIEW_ROLE, PERMISSIONS.CREATE_ROLE] },
  ],

  APPLICATIONS: [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.PLATFORM, actions: [PERMISSIONS.MANAGE_PLATFORM_SETTINGS] },
  ],

  "MODULES & ENTITLEMENTS": [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] },
  ],

  POLICIES: [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
  ],

  SECURITY: [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION, PERMISSIONS.MANAGE_ORG_SESSIONS] },
  ],

  "DATA MANAGEMENT": [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EXPORT_ORG_DATA, PERMISSIONS.EDIT_ORGANIZATION] },
  ],

  MONITORING: [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_AUDIT_LOGS, PERMISSIONS.MANAGE_AUDIT_LOGS, PERMISSIONS.VIEW_ORG_ANALYTICS] },
  ],

  INTEGRATIONS: [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.PLATFORM, actions: [PERMISSIONS.MANAGE_PLATFORM_SETTINGS] },
  ],

  "BILLING & SUBSCRIPTION": [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.MANAGE_SUBSCRIPTIONS, PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.PLATFORM, actions: [PERMISSIONS.MANAGE_SUBSCRIPTIONS] },
  ],
};

// ─── Sidebar Item Permission Map ───────────────────────────────────
// Maps individual sidebar item titles → required permissions
// Used for granular item-level filtering within a visible group
export const SIDEBAR_ITEM_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  // CRM System items
  "Leads": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD, PERMISSIONS.CREATE_LEAD] }],
  "Deals / Opportunities": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }, { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "Sales Pipeline": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }],
  "Clients / Accounts": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST, PERMISSIONS.CREATE_CLIENT] }],
  "Contacts": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "Activities": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }, { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "Campaigns": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }],
  "CRM Settings": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],

  // Project Management items
  "Workspaces": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_PROJECT, PERMISSIONS.VIEW_ALL_PROJECT] }],
  "Projects": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_PROJECT, PERMISSIONS.VIEW_ALL_PROJECT, PERMISSIONS.CREATE_PROJECT] }],
  "Tasks": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_TASK, PERMISSIONS.VIEW_ALL_TASKS, PERMISSIONS.CREATE_TASK] }],
  "Boards": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_BOARD, PERMISSIONS.VIEW_ALL_BOARD, PERMISSIONS.CREATE_BOARD] }],
  "Sprints": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_PROJECT] }],
  "Time Tracking": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_PROJECT] }],
  "PM Settings": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.EDIT_PROJECT] }],

  // HRM items
  "HR Dashboard": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE] }],
  "Employees": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE, PERMISSIONS.CREATE_EMPLOYEE] }],
  "Attendance": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }, { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "Leave Management": [{ module: MODULES.LEAVE, actions: [PERMISSIONS.MANAGE_EMPLOYE_LEAVE] }, { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_EMPLOYEE_PROFILE] }],
  "Payroll": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL, PERMISSIONS.VIEW_PAYSLIPS] }],
  "Performance Reviews": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.EDIT_EMPLOYEE] }],
  "Recruitment": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.CREATE_JOB_POSTING, PERMISSIONS.REVIEW_APPLICATIONS, PERMISSIONS.HIRE_CANDIDATE] }],
  "HR Settings": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.EDIT_EMPLOYEE] }],

  // Finance items
  "Invoices": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Payments": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Accounting": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }, { module: MODULES.TAX, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Expenses": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],

  // Administration items
  "Organization Profile": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_ORG, PERMISSIONS.EDIT_ORGANIZATION] }],
  "Business Units": [{ module: MODULES.FIRM, actions: [PERMISSIONS.VIEW_FIRM, PERMISSIONS.CREATE_FIRM] }],
  "Users": [{ module: MODULES.USER, actions: [PERMISSIONS.VIEW_ALL_USERS, PERMISSIONS.CREATE_USER] }],
  "Roles & Permissions": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.VIEW_ROLE, PERMISSIONS.CREATE_ROLE, PERMISSIONS.MANAGE_PERMISSIONS] }],
  "Workflow Automation": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Security Overview": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION, PERMISSIONS.MANAGE_ORG_SESSIONS] }],
  "Audit Logs": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_AUDIT_LOGS, PERMISSIONS.MANAGE_AUDIT_LOGS] }],
  "Audit Log": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_AUDIT_LOGS, PERMISSIONS.MANAGE_AUDIT_LOGS] }],

  // Admin sidebar specific items
  "Overview": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_ORG] }],
  "Business Units (Firms)": [{ module: MODULES.FIRM, actions: [PERMISSIONS.VIEW_FIRM, PERMISSIONS.CREATE_FIRM] }],
  "Branding & Theme": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Subscription & Billing": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.MANAGE_SUBSCRIPTIONS, PERMISSIONS.EDIT_ORGANIZATION] }],
  "Org Settings": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Org Admins": [{ module: MODULES.USER, actions: [PERMISSIONS.VIEW_ALL_USERS] }, { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],

  // Identity & Access items
  "Teams / Groups": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_TEAM, PERMISSIONS.CREATE_TEAM] }],
  "Authentication": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION, PERMISSIONS.MANAGE_ORG_SESSIONS] }],
  "SSO & Identity Providers": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Login Policies": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Sessions": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.MANAGE_ORG_SESSIONS] }],
};

// ─── HRM Sidebar Permission Map ───────────────────────────────────
// Maps HRM sidebar section titles → required permissions
// null/empty = everyone can see, otherwise user needs at least one matching permission
export const HRM_SIDEBAR_GROUP_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  "Home": [],  // Everyone
  "Me": [],    // Everyone (Self scope)
  "Inbox": [], // Everyone
  "My Team": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.MANAGE_ATTENDANCE] },
    { module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE, PERMISSIONS.APPROVE_TIMESHEETS] },
  ],
  "Organization": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE] },
    { module: MODULES.EMPLOYEE, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] },
  ],
  "Hire": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.CREATE_EMPLOYEE, PERMISSIONS.CREATE_JOB_POSTING, PERMISSIONS.REVIEW_APPLICATIONS, PERMISSIONS.HIRE_CANDIDATE] },
  ],
  "Lifecycle": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.CREATE_EMPLOYEE, PERMISSIONS.EDIT_EMPLOYEE] },
    { module: MODULES.ONBOARDING, actions: [PERMISSIONS.CREATE_EMPLOYEE] },
  ],
  "Time & Attend": [
    { module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] },
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE] },
  ],
  "Payroll": [
    { module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL, PERMISSIONS.VIEW_PAYSLIPS] },
  ],
  "Performance": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.EDIT_EMPLOYEE, PERMISSIONS.APPROVE_TIMESHEETS] },
  ],
  "Documents": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE] },
    { module: MODULES.DOCUMENT, actions: [PERMISSIONS.UPLOAD_DOCUMENT, PERMISSIONS.DOWNLOAD_DOCUMENT] },
  ],
  "Engage": [], // Everyone can see engagement features
  "Helpdesk": [], // Everyone can see (filtered by scope on data level)
  "Expenses": [], // Everyone can see (filtered by scope — own claims only for employees)
  "Timesheets": [
    { module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE, PERMISSIONS.APPROVE_TIMESHEETS] },
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] },
  ],
  "Reports Hub": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] },
    { module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] },
    { module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] },
  ],
  "Admin": [
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS, PERMISSIONS.CREATE_ROLE, PERMISSIONS.EDIT_ROLE] },
  ],
};

// HRM sub-item level permissions (for items inside each group)
export const HRM_SIDEBAR_ITEM_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  // Organization sub-items
  "Org Dashboard": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "Company Profile": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "Departments": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.MANAGE_ATTENDANCE] }],
  "Designations": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.EDIT_EMPLOYEE] }],
  "Locations": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "Policy Center": [{ module: MODULES.POLICY, actions: [PERMISSIONS.MANAGE_PAYROLL] }, { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.EDIT_EMPLOYEE] }],

  // Hire sub-items
  "Job Openings": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.CREATE_JOB_POSTING] }],
  "Candidates": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.REVIEW_APPLICATIONS] }],
  "Interviews": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.REVIEW_APPLICATIONS] }],
  "Offer Letters": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.HIRE_CANDIDATE] }],
  "Hiring Reports": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "Career Page": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.CREATE_JOB_POSTING] }],
  "Resume Parser": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.REVIEW_APPLICATIONS] }],

  // Time & Attend sub-items
  "Shifts & Holidays": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }],
  "Overtime": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }],
  "Shift Allowance": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }],
  "Geo-fencing": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }],
  "Biometric": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }],
  "Sandwich Rules": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }],

  // Payroll sub-items
  "Salary Processing": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],
  "Payroll Reports": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],
  "Payroll Settings": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],
  "Salary Structure": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],
  "Statutory Compliance": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],
  "Loans & Advances": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],
  "Salary Revision": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],
  "Multi-Entity": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],

  // Performance sub-items
  "Calibration": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.EDIT_EMPLOYEE] }],
  "PIP Tracking": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.EDIT_EMPLOYEE] }],
  "Compensation Review": [{ module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL] }],

  // Documents sub-items
  "HR Documents": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "Bulk Letters": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],

  // Helpdesk sub-items (restricted for non-admin)
  "Support Queue": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "Agent Management": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],

  // Expenses sub-items (restricted)
  "Travel": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],

  // Admin sub-items — all require admin-level permissions
  "Role & Permissions": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS, PERMISSIONS.CREATE_ROLE] }],
  "Workflows & Approvals": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] }],
  "Automation & Rules": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] }],
  "Attendance Rules": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }, { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] }],
  "Delegation": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] }],
  "Escalation Rules": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] }],
};

// ─── Lead Management Sidebar Permission Map ───────────────────────
export const LEAD_SIDEBAR_GROUP_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  "Overview": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] },
  ],
  "Lead Inbox": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] },
  ],
  "Leads": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] },
  ],
  "Pipeline": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] },
  ],
  "Activities": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] },
  ],
  "Qualification & Scoring": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.EDIT_LEAD, PERMISSIONS.ASSIGN_LEAD] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] },
  ],
  "Routing & SLA": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.ASSIGN_LEAD] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] },
  ],
  "Automation": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.EDIT_LEAD, PERMISSIONS.ASSIGN_LEAD] },
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
  ],
  "Campaigns & Sources": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD, PERMISSIONS.CREATE_LEAD] },
  ],
  "Reports & Analytics": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] },
    { module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] },
  ],
  "Integrations": [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] },
  ],
  "Settings": [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] },
  ],
};

// Lead Management sub-item permissions
export const LEAD_SIDEBAR_ITEM_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  // Lead Inbox sub-items
  "Unassigned": [{ module: MODULES.LEAD, actions: [PERMISSIONS.ASSIGN_LEAD] }],

  // Leads sub-items
  "Archived": [{ module: MODULES.LEAD, actions: [PERMISSIONS.DELETE_LEAD, PERMISSIONS.EDIT_LEAD] }],
  "Saved Views": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }],

  // Pipeline sub-items
  "Forecast": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }, { module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] }],

  // Activities sub-items
  "Overdue": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD, PERMISSIONS.EDIT_LEAD] }],

  // Qualification sub-items — all admin/manager level
  "Qualification Framework": [{ module: MODULES.LEAD, actions: [PERMISSIONS.EDIT_LEAD, PERMISSIONS.ASSIGN_LEAD] }],
  "Scoring Rules": [{ module: MODULES.LEAD, actions: [PERMISSIONS.EDIT_LEAD, PERMISSIONS.ASSIGN_LEAD] }],
  "Behavioral Scoring": [{ module: MODULES.LEAD, actions: [PERMISSIONS.EDIT_LEAD] }],

  // Routing sub-items — admin only
  "Routing Rules": [{ module: MODULES.LEAD, actions: [PERMISSIONS.ASSIGN_LEAD] }],
  "Assignment Methods": [{ module: MODULES.LEAD, actions: [PERMISSIONS.ASSIGN_LEAD] }],
  "SLA Policies": [{ module: MODULES.LEAD, actions: [PERMISSIONS.ASSIGN_LEAD] }],

  // Automation sub-items
  "Nurture Sequences": [{ module: MODULES.LEAD, actions: [PERMISSIONS.EDIT_LEAD] }],
  "Automation Settings": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],

  // Campaigns sub-items
  "UTM Tracking": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }],
  "Lead Attribution": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }],
  "Tracking Settings": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],

  // Reports sub-items
  "Custom Reports": [{ module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Scheduled Reports": [{ module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] }],

  // Integrations sub-items — all admin only
  "API & Webhooks": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Integration Logs": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_AUDIT_LOGS] }],

  // Settings sub-items — all admin only
  "Organization & Preferences": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Users & Access": [{ module: MODULES.USER, actions: [PERMISSIONS.VIEW_ALL_USERS] }],
  "Lead Lifecycle Setup": [{ module: MODULES.LEAD, actions: [PERMISSIONS.EDIT_LEAD] }],
  "Fields & Data Model": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Security": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Audit & Compliance": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_AUDIT_LOGS] }],
  "Billing & Plan": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.MANAGE_SUBSCRIPTIONS] }],
};

// ─── Client Management Sidebar Permission Map ────────────────────
export const CLIENT_SIDEBAR_GROUP_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  "Overview": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
  ],
  "Revenue": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
  ],
  "Subscriptions": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
  ],
  "Customers": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
  ],
  "Communication": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
  ],
  "Support": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
  ],
  "Analytics": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
    { module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] },
  ],
  "Reports": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] },
    { module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] },
  ],
  "Finance": [
    { module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] },
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
  ],
  "Automation": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.EDIT_CLIENT] },
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
  ],
  "Integrations": [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] },
  ],
  "Settings": [
    { module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] },
    { module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] },
  ],
};

// Client Management sub-item permissions
export const CLIENT_SIDEBAR_ITEM_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  // Revenue sub-items
  "Opportunities": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "Renewals": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "Expansion": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.EDIT_CLIENT] }],

  // Subscriptions sub-items
  "Plans & Pricing": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.EDIT_CLIENT] }],
  "Usage Billing": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Contracts": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "Invoices & Payments": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],

  // Support sub-items
  "SLA Management": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.EDIT_CLIENT] }],
  "Escalations": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.EDIT_CLIENT] }],

  // Analytics sub-items
  "Cohort Analysis": [{ module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Forecasting": [{ module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "AI Insights": [{ module: MODULES.REPORTS, actions: [PERMISSIONS.GENERATE_REPORT] }],

  // Finance sub-items — all admin/finance only
  "Accounting": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Tax Module": [{ module: MODULES.TAX, actions: [PERMISSIONS.GENERATE_REPORT] }],
  "Revenue Recognition": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],

  // Automation sub-items
  "Playbooks": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.EDIT_CLIENT] }],
  "Triggers & Actions": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Notification Rules": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],

  // Integrations sub-items — all admin
  "API Keys & Access": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Webhooks": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "Data Sync Mapping": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
  "AI Integrations": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],

  // Settings sub-items — all admin
  "User Management": [{ module: MODULES.USER, actions: [PERMISSIONS.VIEW_ALL_USERS] }],
  "Roles & Permissions": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.MANAGE_PERMISSIONS] }],
  "Customization": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
};

// ─── Dashboard Access Permissions ─────────────────────────────────
// Controls whether a user can access an entire dashboard module
export const DASHBOARD_ACCESS_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  "/hrmcubicle": [
    { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE, PERMISSIONS.CREATE_EMPLOYEE] },
    { module: MODULES.EMPLOYEE, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE] },
    { module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] },
    { module: MODULES.LEAVE, actions: [PERMISSIONS.MANAGE_EMPLOYE_LEAVE] },
    { module: MODULES.PAYROLL, actions: [PERMISSIONS.MANAGE_PAYROLL, PERMISSIONS.VIEW_PAYSLIPS] },
  ],
  "/lead-management": [
    { module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD, PERMISSIONS.CREATE_LEAD, PERMISSIONS.EDIT_LEAD] },
  ],
  "/client-management": [
    { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST, PERMISSIONS.CREATE_CLIENT, PERMISSIONS.EDIT_CLIENT] },
  ],
  "/projectmanagement": [
    { module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_PROJECT, PERMISSIONS.VIEW_ALL_PROJECT, PERMISSIONS.CREATE_PROJECT] },
  ],
};

// ─── Page Route Permission Map ─────────────────────────────────────
// Maps route patterns → required permissions for page-level access control
export const PAGE_ROUTE_PERMISSIONS: Record<string, PermissionRequirement[]> = {
  "/modules/crm/leads": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD, PERMISSIONS.CREATE_LEAD] }],
  "/modules/crm/deals": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }, { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "/modules/crm/pipeline": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }],
  "/modules/crm/clients": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST, PERMISSIONS.CREATE_CLIENT] }],
  "/modules/crm/contacts": [{ module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "/modules/crm/activities": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }, { module: MODULES.CLIENT, actions: [PERMISSIONS.VIEW_CLIENT_LIST] }],
  "/modules/crm/campaigns": [{ module: MODULES.LEAD, actions: [PERMISSIONS.VIEW_LEAD] }],

  "/modules/workspaces": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_PROJECT, PERMISSIONS.VIEW_ALL_PROJECT] }],
  "/modules/workspaces/tasks": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_TASK, PERMISSIONS.VIEW_ALL_TASKS] }],
  "/modules/workspaces/boards": [{ module: MODULES.PROJECT_MANAGEMENT, actions: [PERMISSIONS.VIEW_BOARD, PERMISSIONS.VIEW_ALL_BOARD] }],

  "/modules/hr": [{ module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES, PERMISSIONS.VIEW_EMPLOYEE_PROFILE] }],
  "/modules/attendance": [{ module: MODULES.ATTENDANCE, actions: [PERMISSIONS.MANAGE_ATTENDANCE] }, { module: MODULES.HRM_MANAGEMENT, actions: [PERMISSIONS.VIEW_ALL_EMPLOYEES] }],
  "/modules/leave-management": [{ module: MODULES.LEAVE, actions: [PERMISSIONS.MANAGE_EMPLOYE_LEAVE] }],

  "/modules/invoice": [{ module: MODULES.INVOICE, actions: [PERMISSIONS.GENERATE_REPORT] }],

  "/modules/firm-management": [{ module: MODULES.FIRM, actions: [PERMISSIONS.VIEW_FIRM, PERMISSIONS.CREATE_FIRM] }],

  "/modules/users": [{ module: MODULES.USER, actions: [PERMISSIONS.VIEW_ALL_USERS, PERMISSIONS.CREATE_USER] }],
  "/modules/administration/roles": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.VIEW_ROLE, PERMISSIONS.CREATE_ROLE, PERMISSIONS.MANAGE_PERMISSIONS] }],
  "/modules/administration/permissions": [{ module: MODULES.ROLE_PERMISSION, actions: [PERMISSIONS.VIEW_ROLE, PERMISSIONS.MANAGE_PERMISSIONS] }],

  "/modules/organization": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_ORG, PERMISSIONS.EDIT_ORGANIZATION] }],

  "/security": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION, PERMISSIONS.MANAGE_ORG_SESSIONS] }],
  "/audit-logs": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.VIEW_AUDIT_LOGS, PERMISSIONS.MANAGE_AUDIT_LOGS] }],

  "/modules/settings": [{ module: MODULES.ORGANIZATION, actions: [PERMISSIONS.EDIT_ORGANIZATION] }],
};
