
"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Image from "next/image"
import { generateQr, verifyQr } from "@/hooks/authHooks"
import { showWarning } from "@/utils/toast"

export default function TwoFASetupPage() {
  const [step, setStep] = useState(1)
  const [otp, setOtp] = useState("")
  const [qrUrl, setQrUrl] = useState<string | null>(null)
  const router = useRouter()

  useEffect(() => {
    const fetchQr = async () => {
      try {
        const response = await generateQr()
        // Assuming API returns { qrUrl: "..." }
        setQrUrl(response.data.qrImageUrl)
      } catch (err) {
        console.error("Failed to fetch QR code", err)
      }
    }

    fetchQr()
  }, [])

  const handleNext = () => setStep(2)

  const handleOtpSubmit = async () => {
    if (otp.trim().length !== 6) {
      showWarning("Please enter a valid 6-digit OTP")
      return
    }

    try {
      const response = await verifyQr(otp)

      if (response.data.success) {
        localStorage.setItem("2fa_enabled", "true")
        router.push("/auth/signin")
      } else {
        alert("OTP verification failed. Please try again.")
      }
    } catch (error: any) {
      alert(error.response?.data?.message || "OTP verification failed")
    }
  }

  return (
    <div className="twofa-setup-container p-8 max-w-lg mx-auto">
      <h1 className="twofa-title text-2xl font-bold mb-4">2FA Setup</h1>

      {step === 1 && (
        <div className="twofa-step1">
          <p className="twofa-instruction mb-4">
            Scan the QR code below using Google Authenticator or any compatible app.
          </p>

          <div className="twofa-qr-wrapper flex justify-center mb-6">
            {qrUrl ? (
              <Image
                src={qrUrl}
                alt="QR Code"
                width={200}
                height={200}
                className="twofa-qr-image"
              />
            ) : (
              <p className="twofa-qr-loading">Loading QR code...</p>
            )}
          </div>

          <Button
            onClick={handleNext}
            disabled={!qrUrl}
            className="twofa-next-btn"
          >
            Next
          </Button>
        </div>
      )}

      {step === 2 && (
        <div className="twofa-step2">
          <p className="twofa-otp-instruction mb-2">
            Enter the 6-digit OTP generated by your authenticator app.
          </p>

          <Input
            type="text"
            maxLength={6}
            pattern="\d*"
            placeholder="Enter OTP"
            value={otp}
            onChange={(e) => setOtp(e.target.value)}
            className="twofa-otp-input mb-4"
          />

          <Button
            onClick={handleOtpSubmit}
            className="twofa-submit-btn"
          >
            Submit
          </Button>
        </div>
      )}
    </div>
  )
}
